# DataSource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1 # userdb 스키마에 mem인 메모리 데이터 베이스로 동작

# MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

# 패키지 명을 생략할 수 있도록 alias 설정
#mybatis.type-aliases-package=com.example.sangwook.model

# mapper 로그레벨 설정
